# docker-compose.yml
services:
  backend:
    image: ghcr.io/ancarpan/fableflow:latest
    ports: ["8080:8080"]
    environment:
      - CONTAINER_MODE=backend
      - FF_HOST=0.0.0.0
      - FF_PORT=8080
    volumes:
      - ./data/ebooks:/ebooks
      - ./data/database:/database
      - ${FF_IMPORT_DIR:-./data/import}:/import
      - ./data/quarantine:/quarantine
      - ./data/logs:/logs

  frontend:
    image: ghcr.io/ancarpan/fableflow:latest
    ports: ["3000:3000"]
    environment:
      - CONTAINER_MODE=frontend
      - FF_BACKEND_ADDR=http://backend:8080
    depends_on: [backend]

