# Ebook Manager Configuration

# Server settings
server:
  host: "localhost"  # IP to bind to (use "0.0.0.0" to allow external connections)
  port: "8080"       # Port to listen on

# Library settings
library:
  scan_directory: "/Users/acarpani/P/ebooks"  # Default directory to scan for ebooks
  auto_scan: true                            # Automatically scan on startup (true/false)

# Database settings (optional - uses defaults if not specified)
database:
  path: "./ebooks.db"  # Path to SQLite database file