# Ebook Manager Configuration

# Server settings
server:
  host: "localhost"  # IP to bind to (use "0.0.0.0" to allow external connections)
  port: "8080"       # Port to listen on
  serve_static_assets: true  # Whether to serve static files (frontend) from backend

# Library settings
library:
  scan_directory: "../data/ebooks"  # Default directory to scan for ebooks
  auto_scan: true                            # Automatically scan on startup (true/false)
  import_directory: "../data/ebooks"  # Directory to scan for books to import
  quarantine_directory: "../data/quarantine"  # Directory for files with missing metadata

# Temporary directory settings
tmp_dir: "/tmp/fableflow"  # Directory for temporary files (conversions, downloads, etc.)

# Logging settings
logdir: "../data/logs"  # Directory for import session logs
max_import_logs: 10  # Maximum number of import session logs to keep

# Database settings (optional - uses defaults if not specified)
database:
  path: "../data/ebooks.db"  # Path to SQLite database file
